---
name: lab-10
break: true
indent: 4
---
src/main:
    java:
        labten/DisplayLibrary.java:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
            MatchFileFragment --fragment "import java.util.ArrayList" --count 1 --exact
            MatchFileFragment --fragment " = new Book()" --count 1 --exact
            MatchFileFragment --fragment "setTitle(" --count 1 --exact
            MatchFileFragment --fragment "setAuthor(" --count 1 --exact
            MatchFileFragment --fragment "setPages(" --count 1 --exact
            MatchFileFragment --fragment "while (" --count 3
            MatchFileFragment --fragment ".get(" --count 1 --exact
            MatchFileFragment --fragment ".size(" --count 1
            CountSingleLineComments --language Java --count 10
            
src/main:
    java:
        labten/Book.java:
            ConfirmFileExists
            
writing:
    reflection.md:
        ConfirmFileExists
        CountFileWords --count 350
        CountFileParagraphs --count 6
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountMarkdownTags --tag "code_block" --count 3

CountCommits --count 3
ExecuteCommand --command "gradle build"
CountCommandOutput --command "gradle -q --console plain run" --count 62
MatchCommandFragment --command "gradle run" --fragment "20" --count 1 --exact
MatchCommandFragment --command "gradle run" --fragment "3.29" --count 1 --exact